name: eataweek-back
services:
    #eataweek-api:
    #    container_name: eataweek
    #    environment:
    #        MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin:9411/api/v2/spans
    #    ports:
    #        - 8080:8080
    #    networks:
    #        - eataweek-net
    #    image: eataweek-api
#    collector:
#        image: otel/opentelemetry-collector:0.103.1
#        extra_hosts: ['host.docker.internal:host-gateway']
#        volumes:
#            - ./docker/otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
#        ports:
#            - 1888:1888 # pprof extension
#            - 8888:8888 # Prometheus metrics exposed by the collector
#            - 8889:8889 # Prometheus exporter metrics
#            - 13133:13133 # health_check extension
#            - 4318:4318 # OTLP http receiver (for metrics and spans)
#            - 55679:55679 # zpages extension
    vault:
        container_name: "guide-vault"
        image: hashicorp/vault:latest
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
        ports:
            - "8200:8200"
    zipkin:
        image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
        extra_hosts: ['host.docker.internal:host-gateway']
        # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
        environment:
        - STORAGE_TYPE=mem
        # Uncomment to enable self-tracing
        # - SELF_TRACING_ENABLED=true
        # Uncomment to increase heap size
        # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
        ports:
        - 9411:9411
        #networks:
        #    - eataweek-net
    prometheus:
        image: prom/prometheus:v2.54.1 # https://hub.docker.com/r/prom/prometheus
        extra_hosts: ['host.docker.internal:host-gateway']
        command:
            - --enable-feature=exemplar-storage
            - --enable-feature=otlp-write-receiver
            - --web.enable-remote-write-receiver
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - prometheus:/prometheus
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - "9090:9090"
        #networks:
        #    - eataweek-net
    grafana:
        image: grafana/grafana:10.4.10 # https://hub.docker.com/r/grafana/grafana/tags
        extra_hosts: ['host.docker.internal:host-gateway']
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        volumes:
            - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
            - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
            - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
        ports:
            - "3000:3000"
        #networks:
        #    - eataweek-net
    tempo:
        image: grafana/tempo:2.4.2 # https://hub.docker.com/r/grafana/tempo/tags and https://github.com/grafana/tempo/releases
        extra_hosts: ['host.docker.internal:host-gateway']
        command: ['-config.file=/etc/tempo.yml']
        volumes:
            - tempo:/tmp/tempo
            - ./docker/grafana/tempo.yml:/etc/tempo.yml:ro
        ports:
            - "3200:3200"    # tempo
            - "4318:4318"  # otlp http
       # networks:
        #    - eataweek-net
    loki:
        image: grafana/loki:3.1.2 # https://hub.docker.com/r/grafana/loki/tags and https://github.com/grafana/loki/releases
        extra_hosts: ['host.docker.internal:host-gateway']
        command: ['-config.file=/etc/loki/local-config.yaml']
        ports:
            - "3100:3100"
        #networks:
        #    - eataweek-net
volumes:
    prometheus:
        driver: local
    tempo:
        driver: local
#networks:
#    eataweek-net:
#        external: true
#        name: eataweek-net